LIST(APPEND DVC_NAMES dvc )
FIND_LIBRARY(DVC_LIBRARY NAMES ${DVC_NAMES} )

SET( GINGA_SOURCE_FILES
	src/main.cpp
)

IF(NOT ${DVC_LIBRARY} MATCHES NOTFOUND)
	MESSAGE("DVC_LIBRARY = ${DVC_LIBRARY}")
        LIST(APPEND GINGA_LINK_LIBRARIES dvc )
ENDIF(NOT ${DVC_LIBRARY} MATCHES NOTFOUND)


