SET( NCL-PRESENTER_HEADER_FILES
	include/FormatterScheduler.h
	include/editingcommandevents.h
	include/IFormatterSchedulerListener.h
	include/adapters/text/SubtitlePlayerAdapter.h
	include/adapters/text/PlainTxtPlayerAdapter.h
	include/adapters/application/declarative/xhtml/LinksPlayerAdapter.h
	include/adapters/application/declarative/ncl/NCLPlayerAdapter.h
	include/adapters/application/imperative/lua/LuaPlayerAdapter.h
	include/adapters/application/ApplicationPlayerAdapter.h
	include/adapters/remote/RemotePlayerAdapter.h
	include/adapters/IPlayerAdapterManager.h
	include/adapters/image/ImagePlayerAdapter.h
	include/adapters/INclEditListener.h
	include/adapters/AdaptersComponentSupport.h
	include/adapters/FormatterPlayerAdapter.h
	include/adapters/NominalEventMonitor.h
	include/adapters/av/AVPlayerAdapter.h
	include/adapters/IPlayerAdapter.h
	include/adapters/PlayerAdapterManager.h
	include/animation/AnimationController.h
	include/model/FormatterLayout.h
	include/model/ApplicationExecutionObject.h
	include/model/CompositeExecutionObject.h
	include/model/LinkRepeatAction.h
	include/model/FormatterRegion.h
	include/model/SwitchEvent.h
	include/model/LinkCondition.h
	include/model/LinkValueAssessment.h
	include/model/LinkTransitionTriggerCondition.h
	include/model/IFormatterEvent.h
	include/model/EventTransition.h
	include/model/LinkAssessmentStatement.h
	include/model/LinkStatement.h
	include/model/LinkTriggerListener.h
	include/model/LinearCostFunctionDuration.h
	include/model/FormatterLink.h
	include/model/IEventListener.h
	include/model/AnchorEvent.h
	include/model/FlexibleTimeMeasurement.h
	include/model/ExecutionObject.h
	include/model/TimeMeasurement.h
	include/model/ExecutionObjectSwitch.h
	include/model/LinkAttributeAssessment.h
	include/model/LinkAndCompoundTriggerCondition.h
	include/model/SelectionEvent.h
	include/model/CostFunctionDuration.h
	include/model/LinkAssignmentAction.h
	include/model/UnflexibleDuration.h
	include/model/EventTransitionManager.h
	include/model/LinkActionListener.h
	include/model/FormatterEvent.h
	include/model/LinkListener.h
	include/model/TransitionDispatcher.h
	include/model/FormatterCausalLink.h
	include/model/EndEventTransition.h
	include/model/LinkAssessment.h
	include/model/IAttributeValueMaintainer.h
	include/model/CascadingDescriptor.h
	include/model/LinkSimpleAction.h
	include/model/PresentationEvent.h
	include/model/LinkAction.h
	include/model/DurationFactory.h
	include/model/LinkCompoundTriggerCondition.h
	include/model/FocusSourceManager.h
	include/model/LinkTriggerCondition.h
	include/model/LinkCompoundStatement.h
	include/model/AttributionEvent.h
	include/model/LinkActionProgressionListener.h
	include/model/NodeNesting.h
	include/model/BeginEventTransition.h
	include/model/LinkCompoundAction.h
	include/model/FormatterDeviceRegion.h
	include/emconverter/ObjectCreationForbiddenException.h
	include/emconverter/FormatterLinkConverter.h
	include/emconverter/FormatterConverter.h
	include/multidevice/FormatterBaseDevice.h
	include/multidevice/IFormatterMultiDevice.h
	include/multidevice/FormatterPassiveDevice.h
	include/multidevice/FormatterActiveDevice.h
	include/multidevice/FormatterMultiDevice.h
	include/multidevice/FMDComponentSupport.h
	include/FormatterMediator.h
	include/privatebase/PrivateBaseManager.h
	include/privatebase/PrivateBaseContext.h
	include/privatebase/IPrivateBaseManager.h
	include/adaptation/context/RuleAdapter.h
	include/adaptation/context/ContextBase.h
	include/adaptation/context/PresentationContext.h
	include/prefetch/PrefetchManager.h
	include/prefetch/IPrefetchManager.h
	include/focus/FormatterFocusManager.h
	include/gfx/GingaNclGfx.h
)

SET( NCL-PRESENTER_SOURCE_FILES
	${NCL-PRESENTER_HEADER_FILES}
	src/FormatterScheduler.cpp
	src/adapters/text/SubtitlePlayerAdapter.cpp
	src/adapters/text/PlainTxtPlayerAdapter.cpp
	src/adapters/application/declarative/xhtml/LinksPlayerAdapter.cpp
	src/adapters/application/declarative/ncl/NCLPlayerAdapter.cpp
	src/adapters/application/ApplicationPlayerAdapter.cpp
	src/adapters/application/imperative/lua/LuaPlayerAdapter.cpp
	src/adapters/PlayerAdapterManager.cpp
	src/adapters/FormatterPlayerAdapter.cpp
	src/adapters/image/ImagePlayerAdapter.cpp
	src/adapters/av/AVPlayerAdapter.cpp
	src/adapters/NominalEventMonitor.cpp
	src/editingcommandevents.cpp
	src/animation/AnimationController.cpp
	src/model/event/FormatterEvent.cpp
	src/model/event/transition/EventTransition.cpp
	src/model/event/transition/EndEventTransition.cpp
	src/model/event/transition/BeginEventTransition.cpp
	src/model/event/transition/EventTransitionManager.cpp
	src/model/event/transition/TransitionDispatcher.cpp
	src/model/event/AnchorEvent.cpp
	src/model/event/PresentationEvent.cpp
	src/model/event/SelectionEvent.cpp
	src/model/event/AttributionEvent.cpp
	src/model/presentation/FormatterDeviceRegion.cpp
	src/model/presentation/CascadingDescriptor.cpp
	src/model/presentation/FormatterLayout.cpp
	src/model/presentation/focus/FocusSourceManager.cpp
	src/model/presentation/FormatterRegion.cpp
	src/model/switches/ExecutionObjectSwitch.cpp
	src/model/switches/SwitchEvent.cpp
	src/model/time/TimeMeasurement.cpp
	src/model/time/CostFunctionDuration.cpp
	src/model/time/FlexibleTimeMeasurement.cpp
	src/model/time/UnflexibleDuration.cpp
	src/model/time/LinearCostFunctionDuration.cpp
	src/model/time/DurationFactory.cpp
	src/model/components/ExecutionObject.cpp
	src/model/components/ApplicationExecutionObject.cpp
	src/model/components/CompositeExecutionObject.cpp
	src/model/components/NodeNesting.cpp
	src/model/link/LinkValueAssessment.cpp
	src/model/link/FormatterLink.cpp
	src/model/link/LinkCompoundTriggerCondition.cpp
	src/model/link/LinkTransitionTriggerCondition.cpp
	src/model/link/LinkAttributeAssessment.cpp
	src/model/link/LinkRepeatAction.cpp
	src/model/link/LinkSimpleAction.cpp
	src/model/link/FormatterCausalLink.cpp
	src/model/link/LinkTriggerCondition.cpp
	src/model/link/LinkAndCompoundTriggerCondition.cpp
	src/model/link/LinkAssessmentStatement.cpp
	src/model/link/LinkAssignmentAction.cpp
	src/model/link/LinkCompoundStatement.cpp
	src/model/link/LinkAction.cpp
	src/model/link/LinkCompoundAction.cpp
	src/FormatterMediator.cpp
	src/emconverter/FormatterConverter.cpp
	src/emconverter/FormatterLinkConverter.cpp
	src/multidevice/FormatterPassiveDevice.cpp
	src/multidevice/FormatterActiveDevice.cpp
	src/multidevice/FormatterBaseDevice.cpp
	src/multidevice/FormatterMultiDevice.cpp
	src/privatebase/PrivateBaseManager.cpp
	src/privatebase/PrivateBaseContext.cpp
	src/adaptation/context/PresentationContext.cpp
	src/adaptation/context/RuleAdapter.cpp
	src/adaptation/context/ContextBase.cpp
	src/prefetch/PrefetchManager.cpp
	src/focus/FormatterFocusManager.cpp
	src/gfx/GingaNclGfx.cpp
)
