/* config.h template for cmake */
#define ${PROJECT_NAME_UPPERCASE}_VERSION ${VERSION}

/* Def to 1 if you have Component support. */
#define HAVE_COMPSUPPORT ${HAVE_COMPSUPPORT}

/* Def to 1 if you have timer support. */
#define HAVE_CLOCKTIME ${HAVE_CLOCKTIME}

/* Def to 1 if you have FFMpeg support */
#define HAVE_FFMPEG ${HAVE_FFMPEG}

/* Def to 1 if you have FFMpeg support */
#define HAVE_XINE ${HAVE_XINE}

/* Prefix of the data path*/
#define DATA_PREFIX_PATH "${CMAKE_INSTALL_PREFIX}"

